name: deployment 
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rvrbk/multi-client ./client
      - run: docker build -t rvrbk/multi-nginx ./nginx
      - run: docker build -t rvrbk/multi-server ./server
      - run: docker build -t rvrbk/multi-worker ./worker
      #- run: docker build -t rvrbk/react-test -f Dockerfile.dev .
      #- run: docker run -e CI=true rvrbk/react-test npm test
      - name: deploy package
        run: zip -r deploy.zip . -x '*.git*'
      - name: beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-us-east-1-252439019993
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip